### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by lucatoss** [Sotrosca/zona-prop-scraper#1]
Hola, ejecuté "zonaprop-scrapping.py" con la siguiente URL: https://www.zonaprop.com.ar/departamentos-alquiler-avellaneda y me arrojó el error HTTP Error 403: Forbidden.

Estoy ejecutando desde Windows y leí por ahí que eso puede ser un problema. No tengo mucha experiencia en este tipo de código, y me sería de mucha ayuda una mano. Gracias!

**Comment by Sotrosca** [comment]
Hola lucatoss cómo andás?

Ahí lo probé y tengo el mismo error.

Dejame revisarlo porque puede ser que haya cambiado la página y haya que mandar alguna especie de token al realizar la request.

**Comment by lucatoss** [comment]
Si!, estuve leyendo un poco y aparentemente es algún cambio en la página. Si logras dar en el clavo me sería de gran ayuda! quiero hacer un análisis parecido al que hiciste vos, pero metiendo otras variables

**Comment by Sotrosca** [comment]
Al parecer zonaprop utiliza Cloudflare ahora.

El scrapper no es capaz de pasar la validación de que no es un bot y por lo tanto Cloudflare devuelve el 403.

Revisé el robots.txt de la web y no agregaron nada sobre lo scrappear la información que estamos queriendo buscar, por lo que voy a intentar ver si puedo mejorar el scrapper para que supere la validación de Cloudflare.

Si por casualidad encontrás cómo hacerlo, sé libre de mandar un pull request con los cambios.

**Comment by tomasHolaHello** [comment]
Hola! 
Tratando de resolver "HTTP Error 403: Forbidden", en algún foro leí que CLOUDSCRAPER logra saltear los artilugios anti-bot de Cloudflare. La librería esta disponible para python también. Intente un buen rato, pero no supe implementarla. 
Les tiro la data por ahi se dan cuenta de cómo hacerlo andar.
Sludos!

**Comment by Sotrosca** [comment]
Hola tomasHolaHello, ayer estuve haciendo pruebas de concepto con la librería cloudscraper y dio buenos resultados, por lo que voy a estar trabajando esta semana para implementarla en el proyecto.

Gracias por la info y avisaré por acá cuando tenga el código listo.

**Comment by Sotrosca** [comment]
@tomasHolaHello @lucatoss 

Buenas, cómo andan?

Está subido el cambio con la implementación de cloudscraper junto a mejoras en el diseño del proyecto.

Les agradecería muchísimo si lo prueban y me comentan si les funcionó y si les sirvió.

Estoy trabajando en hacer un análisis de los datos mucho más interesante que el que ya existe aprovechando que cuento con más conocimiento y experiencia hoy en día. Así que si les interesa pronto estaré publicando el análisis.

Además les invito a comentarme los proyectos y/o análisis que puedan llegar a realizar con esta herramienta. Me encataría escuchar sus ideas.

Saludos !!

**Comment by tomasHolaHello** [comment]
@lucatoss 
Como va! 
Estuve haciendo unos tests con los siguientes resultados:

1. la primer vez que intente correrlo me arrojó el siguiente error
![image](https://user-images.githubusercontent.com/109529889/195214254-6d98f2fd-a637-4487-a21c-9a1539f88292.png)
Encontré una solución que no es de mi autoría (fuente: https://github.com/ptrstn/dailyblink/issues/7)
`python -m pip install --upgrade --user git+https://github.com/ptrstn/dailyblink`
Funcionó de maravilla.

2. posteriormente ocurrió otro error relacionado a la falta del folder /data/ dentro de la carpeta /zona-prop-scraper/
Una vez creada funcionó todo de maravilla.

@lucatoss la verdad una tremenda pasada lo tuyo, muchas gracias. Cualquier adelanto de mi parte te lo compartiré.
Abrazo!

**Comment by Sotrosca** [comment]
Qué tal @tomasHolaHello, cómo va?

Calculo que los mensajes van hacia mí, digo porque lo etiquetaste a lucatoss jaja.

Antes que nada te agradezco por interesarte en el proyecto y me alegro que lo encuentres útil.

En cuanto a los errores que me comentas, intenté reproducir el del captcha de Cloudflare pero no sucedió.

Supongo que Cloudflare estará probando esta versión 2 de captchas y por lo tanto no siempre los usa. Voy a esperar a que sea algo recurrente para implementar tu solución ya que puede que hagan cambios en estos captchas y esta solución quede vieja.

Con respecto al folder /data/ voy a hacer un fix para que se cree si no existe.

De vuelta te agradezco por testear el código.

Voy a cerrar este issue, cualquier cosa sentite libre de abrir otro si encontrás algún problema.

Saludos.

**Comment by Sotrosca** [comment]
Listo, ya está subido a la branch `master` el fix del error de la carpeta /data/ inexistente !!

**Comment by Sotrosca** [comment]
@tomasHolaHello  @lucatoss Ya se encuentra el análisis de los datos !!

Se encuentra en la folder `/analysis/`

Saludos y espero que les sirva.
